name: 'Deploy App to Huawei Cloud'
description: '部署应用到华为云（内部自动通过 OIDC 认证）'

inputs:
  huawei-account-id:
    description: '华为云账号 ID'
    required: false
    default: '4d29a984c4fe4e6eb5d404a853d0084e'

outputs:
  deploy-status:
    description: '部署状态'

runs:
  using: 'node20'
  main: 'dist/index.js'
